# Generated by Django 4.0.5 on 2022-06-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
