# Generated by Django 4.0.5 on 2022-06-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_uploadedfiles_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='post',
            field=models.FileField(blank=True, upload_to='posts'),
        ),
    ]
