# Generated by Django 4.0.5 on 2022-06-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_uploadedfiles_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfiles',
            old_name='post',
            new_name='file',
        ),
    ]
