# Generated by Django 4.0.5 on 2022-06-20 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rename_post_uploadedfiles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='post_id',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, related_name='posts_files', to='posts.posts'),
            preserve_default=False,
        ),
    ]
