# Generated by Django 4.0.5 on 2022-06-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_uploadedfiles_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='file',
            field=models.FileField(upload_to='posts'),
        ),
    ]
