# Generated by Django 4.0.5 on 2022-06-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_likes_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
