# Generated by Django 4.0.5 on 2022-06-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_posts_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='updated_on',
        ),
    ]
