# Generated by Django 4.0.5 on 2022-07-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_restrictedusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restrictedusers',
            name='status',
        ),
    ]
