# Generated by Django 4.0.5 on 2022-07-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_restrictedusers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default_bppqii.jpeg', upload_to='profile_picture'),
        ),
    ]
