LIKE_HEADER = 'Post Like'
LIKE_BODY = '{user} Liked your Post titled {title} on {create_date}'
COMMENT_HEADER = 'Post Comment'
COMMENT_BODY = '{} Commented On Post titled {} on {}: "{}"'
FRIEND_REQUEST_HEADER = 'Friend Request'
FRIEND_REQUEST_BODY = '{} had Send you A Friend Request'
ACCEPT_FRIEND_REQUEST_BODY = '{} had Accepted your Friend Request'
BLOCK_USER = "User Blocked successfully."
UNBLOCK_USER = "User UnBlocked successfully."
