# Generated by Django 4.0.5 on 2022-06-29 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('notified_by', models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='notification_due_to', to=settings.AUTH_USER_MODEL)),
                ('notified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
